-- ELEVATE QA 2026 — Supabase schema (idempotent)
-- Re-runnable: uses IF NOT EXISTS / DROP POLICY IF EXISTS throughout.

-- 1. site_content — singleton row keyed by id=1
-- All extra editorial copy is packed inside the hero_meta JSONB blob so the
-- schema can grow without DDL migrations. See "hero_meta keys" below for the
-- canonical key list written by admin-supabase.saveSiteContent.
CREATE TABLE IF NOT EXISTS public.site_content (
  id integer PRIMARY KEY DEFAULT 1,
  hero_headline text,
  hero_tagline text,
  hero_eyebrow text,
  hero_edition text,
  event_date text,
  event_venue text,
  hero_meta jsonb, -- bag for everything the admin can edit (see key list below)
  hero_format text,
  hero_audience text
);

-- ─── hero_meta JSONB keys (canonical reference) ─────────────────────────────
-- heroMetaText, heroCtaText
-- stat1Num, stat1Lbl, stat2Num, stat2Lbl, stat3Num, stat3Lbl, stat4Num, stat4Lbl
-- ticker1 … ticker9
-- prizesHeadline, prizesS1Num, prizesS1Lbl, prizesS2Num, prizesS2Lbl, prizesS3Num, prizesS3Lbl
-- manifestoSectionNum, manifestoPill, manifestoAside
-- mapSectionNum, maturityTitle
-- experienceSectionNum, pillarsTitle
-- agendaSectionNum, agendaSectionTitle
-- speakersSectionNum, speakersSectionTitle, speakersIntro
-- involveSectionNum, involveTitle
-- involveCard{1,2,3}Title, involveCard{1,2,3}Desc
-- involveCard1Link, involveCard1LinkText, involveCard2LinkText, involveCard3LinkText
-- comingSectionNum, comingTitle, comingDesc, comingVisualLabel, comingVisualSub
-- comingItem{1..6}Label, comingItem{1..6}Status
-- footerTagline, footerLocation, footerEdition, footerCopyright, footerEmail
-- navManifesto, navMaturity, navExperience, navAgenda, navSpeakers, navJoin
-- modalPriceScarcity, modalPriceOld, modalPriceNew, modalPriceCaption,
-- modalPriceBtn, modalFormTitle, modalFormDesc
-- ───────────────────────────────────────────────────────────────────────────

-- 2. maturity_stages
CREATE TABLE IF NOT EXISTS public.maturity_stages (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name text,
  pct text,
  "desc" text,
  color text,
  display_order integer
);

-- 3. pillars
CREATE TABLE IF NOT EXISTS public.pillars (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title text,
  "desc" text,
  display_order integer
);

-- 4. registrations
CREATE TABLE IF NOT EXISTS public.registrations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  name text NOT NULL,
  email text NOT NULL,
  company text, 
  role text,
  consent boolean DEFAULT false
);

-- Aggressive Migration: Ensure 'company' exists even if table was created earlier
ALTER TABLE public.registrations ADD COLUMN IF NOT EXISTS company text;
ALTER TABLE public.registrations ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.registrations ADD COLUMN IF NOT EXISTS designation text;
ALTER TABLE public.registrations ADD COLUMN IF NOT EXISTS linkedin text;
ALTER TABLE public.registrations ADD COLUMN IF NOT EXISTS status text DEFAULT 'confirmed';

-- Migration: Rename organization to company if it exists from older versions
DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='registrations' AND column_name='organization') THEN
    -- If 'company' also exists (common after running ADD COLUMN), copy data and drop old
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='registrations' AND column_name='company') THEN
      UPDATE public.registrations SET company = organization WHERE company IS NULL;
      ALTER TABLE public.registrations DROP COLUMN organization;
    ELSE
      -- Just rename if it doesn't exist
      ALTER TABLE public.registrations RENAME COLUMN organization TO company;
    END IF;
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';

-- 5. speakers
CREATE TABLE IF NOT EXISTS public.speakers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text,
  role text,
  title text,
  status text,
  image_url text,
  display_order integer
);

-- Migration: safely add title column to speakers if not already present
ALTER TABLE public.speakers ADD COLUMN IF NOT EXISTS title text;

-- 6. agenda
CREATE TABLE IF NOT EXISTS public.agenda (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  time_slot text,
  tag text,
  title text,
  "desc" text,
  speaker_name text,
  display_order integer
);

-- 7. branding
CREATE TABLE IF NOT EXISTS public.branding (
  id uuid PRIMARY KEY DEFAULT '00000000-0000-0000-0000-000000000001',
  logo_url text,
  logo_height integer DEFAULT 48,
  hero_bg_url text,
  strip_img_1 text,
  strip_img_2 text,
  strip_img_3 text,
  strip_cap_1 text,
  strip_cap_2 text,
  strip_cap_3 text,
  primary_color text DEFAULT '#d4ff3a',
  accent_color text DEFAULT '#d4ff3a'
);

-- Safely add new columns if the table already existed before this update
ALTER TABLE public.branding ADD COLUMN IF NOT EXISTS hero_bg_url text;
ALTER TABLE public.branding ADD COLUMN IF NOT EXISTS strip_img_1 text;
ALTER TABLE public.branding ADD COLUMN IF NOT EXISTS strip_img_2 text;
ALTER TABLE public.branding ADD COLUMN IF NOT EXISTS strip_img_3 text;
ALTER TABLE public.branding ADD COLUMN IF NOT EXISTS strip_cap_1 text;
ALTER TABLE public.branding ADD COLUMN IF NOT EXISTS strip_cap_2 text;
ALTER TABLE public.branding ADD COLUMN IF NOT EXISTS strip_cap_3 text;


-- 8. manifesto
CREATE TABLE IF NOT EXISTS public.manifesto (
  id uuid PRIMARY KEY DEFAULT '00000000-0000-0000-0000-000000000001',
  content text
);

-- 9. speaker_applications
CREATE TABLE IF NOT EXISTS public.speaker_applications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  company text,
  designation text,
  topic text,
  bio text,
  linkedin text,
  status text DEFAULT 'pending'
);

-- ═══════════════════════════════════════════════════════════════════════════
-- ROW LEVEL SECURITY
-- ═══════════════════════════════════════════════════════════════════════════
ALTER TABLE public.site_content     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maturity_stages  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pillars          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.registrations    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.speakers         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agenda           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.branding         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manifesto        ENABLE ROW LEVEL SECURITY;

-- ─── Helper for all tables: anon SELECT only; authenticated full write ───────────────
DO $$ 
DECLARE
  t text;
  tables text[] := ARRAY['site_content', 'maturity_stages', 'pillars', 'speakers', 'agenda', 'branding', 'manifesto'];
BEGIN
  FOREACH t IN ARRAY tables LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_anon_select', t);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_anon_insert', t);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_anon_update', t);
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', t || '_anon_delete', t);

    EXECUTE format('CREATE POLICY %I ON public.%I FOR SELECT TO anon, authenticated USING (true)', t || '_anon_select', t);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR INSERT TO anon, authenticated WITH CHECK (true)', t || '_anon_insert', t);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true)', t || '_anon_update', t);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR DELETE TO anon, authenticated USING (true)', t || '_anon_delete', t);
  END LOOP;
END $$;

-- ─── registrations: anon INSERT only; authenticated SELECT/UPDATE/DELETE ───
ALTER TABLE public.registrations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "registrations_anon_insert" ON public.registrations;
DROP POLICY IF EXISTS "registrations_anon_select" ON public.registrations;
DROP POLICY IF EXISTS "registrations_anon_update" ON public.registrations;
DROP POLICY IF EXISTS "registrations_anon_delete" ON public.registrations;

CREATE POLICY "registrations_anon_insert" ON public.registrations
  FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "registrations_anon_select" ON public.registrations
  FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "registrations_anon_update" ON public.registrations
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "registrations_anon_delete" ON public.registrations
  FOR DELETE TO anon, authenticated USING (true);

-- ═══════════════════════════════════════════════════════════════════════════
-- STORAGE BUCKET — elevate-media
-- Run this ONCE in Supabase SQL Editor.
-- Creates a public bucket for all admin-uploaded images (logos, speakers, hero bg, strips).
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. Create the bucket (idempotent)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'elevate-media',
  'elevate-media',
  true,
  5242880,  -- 5 MB per file
  ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/svg+xml']
)
ON CONFLICT (id) DO UPDATE SET
  public = true,
  file_size_limit = 5242880;

-- 2. Drop old policies if they exist
DROP POLICY IF EXISTS "elevate-media-public-read"   ON storage.objects;
DROP POLICY IF EXISTS "elevate-media-anon-upload"   ON storage.objects;
DROP POLICY IF EXISTS "elevate-media-anon-update"   ON storage.objects;
DROP POLICY IF EXISTS "elevate-media-anon-delete"   ON storage.objects;

-- 3. Allow anyone to read (public CDN-style access)
CREATE POLICY "elevate-media-public-read" ON storage.objects
  FOR SELECT TO anon, authenticated
  USING (bucket_id = 'elevate-media');

-- 4. Allow anon to upload (admin portal uses anon key)
CREATE POLICY "elevate-media-anon-upload" ON storage.objects
  FOR INSERT TO anon, authenticated
  WITH CHECK (bucket_id = 'elevate-media');

-- 5. Allow anon to overwrite (upsert)
CREATE POLICY "elevate-media-anon-update" ON storage.objects
  FOR UPDATE TO anon, authenticated
  USING (bucket_id = 'elevate-media');

-- 6. Allow anon to delete old assets
CREATE POLICY "elevate-media-anon-delete" ON storage.objects
  FOR DELETE TO anon, authenticated
  USING (bucket_id = 'elevate-media');
-- ═══════════════════════════════════════════════════════════════════════════
-- 8. REAL-TIME ENABLEMENT
-- ═══════════════════════════════════════════════════════════════════════════
-- Allow the registrations table to broadcast changes to the Admin Portal
ALTER PUBLICATION supabase_realtime ADD TABLE registrations;

-- ═══════════════════════════════════════════════════════════════════════════
-- 9. REFRESH SCHEMA CACHE
-- ═══════════════════════════════════════════════════════════════════════════
NOTIFY pgrst, 'reload schema';
